name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install
        run: make install

      - name: Generate prod env file
        env:
          HELLO_URL: ${{ secrets.HELLO_URL }}
          SEARCH_URL: ${{ secrets.SEARCH_URL }}
          SEARCH_ENABLED: ${{ secrets.SEARCH_ENABLED }}
        run: |
          touch .env.production
          echo HELLO_URL="$HELLO_URL" >> .env.production
          echo SEARCH_URL="$SEARCH_URL" >> .env.production
          echo SEARCH_ENABLED="$SEARCH_ENABLED" >> .env.production
        shell: bash

      - name: Build
        run: make build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Ingest search docs
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_POSTGRES_ADDON_NAME: ${{ secrets.HEROKU_POSTGRES_ADDON_NAME }}
        run: |
          HEROKU_API_KEY=$HEROKU_API_KEY cat search.sql | heroku pg:psql $HEROKU_POSTGRES_ADDON_NAME --app $HEROKU_APP_NAME
        shell: bash
