name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Downgrade npm
        run: npm install -g npm@6.14.14

      - name: install
        run: make install

      - name: build
        run: make build

      - name: test
        run: make testc
