name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Set Node options
        run: echo "NODE_OPTIONS=--max_old_space_size=2048" >> $GITHUB_ENV

      - name: install
        run: make install

      - name: build
        run: make build

      - name: test
        run: make testc
