name: Temporary Ingest Search Docs Fix

on:
  push:
    branches:
      - chore/cd-fix-ingest-search-docs

jobs:
  ingest-search-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install
        run: make install

      - name: Build
        run: make build

      - name: Ingest search docs
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          HEROKU_API_KEY=$HEROKU_API_KEY cat search.sql | heroku pg:psql $HEROKU_POSTGRES_ADDON_NAME --app $HEROKU_APP_NAME
        shell: bash
